		/// @description Insert description here
// You can write your code in this editor
starty=y
startx=x
disc=0
right=0
left=0
up=0
down=0 


image_xscale=0.875
image_yscale=0.875



depth=-15000

touching=0
level=0
skill=0
MaxLevel=3
skilltype=0
unlock=id
unlock2=id
unlock3=id
unlock4=id
unlock5=id
unlock6=id



require="Na"

desc2="Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text Sample Text"





if OGoblin.form=0

{
g0=IceGui
g1=IceHailGui
g2=IceThornGui
g3=IceGrowthGui
g4=IceDryIceGui
g5=IceBeastialBondGui
g6=IceFreezeGui
g7=IceCrawlGui			
g8=IceFlurryGui
g9=IceFrostSlashGui
g10=IceBreathGui
g11=IceBlastGui
g12=IceSubZeroGui
g13=IceStepGui
g14=IceRuneGui
g15=IceIcicleCrashGui
g16=IceHailFragmentationGui
g17=IceThornPersistenceGui
g18=IceEyeGui
g19=IceThornGardenGui
g20=id
g21=IceGrowthIceTouchGui
g22=IceSlushGui
g23=IceGrowthFrostCoffinGui
g24=IceDryIceIceFogGui
g25=IceFreezingSphereGui
g26=IceDryIceBombGui
g27=IceBeastialBondWhelpsGui
g28=IceRushGui
g29=IceBeastialBondSentMarkerGui
g30=id
g31=IceFreezeHypothermiaGui
g32=InscriptionGui
g33=IceFreezeFrostBiteGui
g34=IceHailStormGui
g35=IceBlizzardGui
g36=IceHailFragmentationHaloGui
g37=IceHailFragmentationBarrageGui
g38=IceThornPersistenceSeeddispersalGui
g39=IceThornPersistenceForeverIceGui
g40=IceBloomGui
g41=IceThornGardenBlueThumbGui
g42=IceThornGardenBallisticDispersalGui
g43=IceGrowthIceTouchSmashGui
g44=IceGrowthGuiIceTouchArractionGui
g45=IceCradleGui
g46=IceGrowthFrostCoffinIcyVeinsGui
g47=IceGrowthFrostCoffinExecutionGui
g48=IceDryIceIceFogWhiteDeathGui
g49=IceDryIceIceFogFreezingFogGui
g50=IceDeepfreezeGui
g51=IceDryIceBombBlackIceGui
g52=IceDryIceBombColdflashGui
g53=IceBeastialBondWhelpsNourishmentGui
g54=IceBeastialBondWhelpsWolfPackGui
g55=IcePuppyLoveGui
g56=IceBeastialBondSentMarkerAlphaOmegaGui
g57=IceBeastialBondSentMarkerFocusedAssultGui
g58=IceFreezeHypothermiaDeliriumGui
g59=IceFreezeHypothermiaNerveDeathGui
g60=IceFormGui
g61=IceFreezeFrostBiteBlackFootGui
g62=IceFreezeFrostBiteShatterGui
g63=IceHailStormFullAutoGui
g64=IceHailStormStoppingPowerGui
g65=IceIceAgeGui
g66=IceBlizzardCuttingWindGui
g67=IceIcicleCrashShardGui
g68=IceBloomRoseGui
g69=IceAnimatedIceGui
g70=IceAnimatedIceLatchGui
g71=IceAnimatedIceSnowdayGui
g72=IceWitchVeparGui
g73=IceBloomSnapGui
g74=IceCradleElasticCollisionGui
g75=IceHoarFrostGui
g76=IceHoarFrostMorningDewGui
g77=IceHoarFrostAdvectionGui
g78=IceIcyEmanationGui
g79=IceCradleCrackGui
g80=IceFreezingSphereSpinnerGui
g81=IceDeepFreezeShiverGui
g82=IceDeepFreezePermaFrostGui
g83=IceGiantIceBallGui
g84=IceFreezingSphereExplosionGui
g85=IcePuppyLoveTrustGui
g86=IceToothAndClawGui
g87=IceToothAndClawSavageBiteGui
g88=IceToothAndClawRavageGui
g89=IceHowlGui
g90=IcePuppyLovePlayTimeGui
g91=IceFormBurstOfIceGui
g92=IceCryoPreservationGui
g93=IceCryoPreservationRushGui
g94=IceCryoPreservationRingGui
g95=IceFrozenTerrorGui
g96=IceFormDecoyGui
g97=IceIcicleCrashDirectedFlowGui
g98=IceBlizzardWhiteoutGui

}
if OGoblin.form=1

{
g0=FireGui
g1=FireballGui
g2=FireMeltGui
g3=FireExplosionGui
g4=FireConcentratedExplosionGui
g5=FireIntensityGui
g6=FireBurnGui
g7=FireFlameShamanGui
g8=FireFlameThrowerGui
g9=FireFlameSpearGui
g10=FireBallBigGui
g11=FireFlameBreathGui
g12=FireBurnPathGui
g13=FireWalkGui
g14=FireRuneGui
g15=FireSpewerGui
g16=FireballPushGui
g17=FireMeltCorrodeGui
g18=FireEyeGui
g19=FireMeltDissolveGui
g20=FireExplosiveDashGui
g21=FireExplosionCenterHeavyGui
g22=FireFlameCrushGui
g23=FireExplosionRangeGui
g24=FireConcentratedExplosionMirvGui
g25=FireFlameMissileGui
g26=FireConcentratedExplosionImplosionGui
g27=FireIntensitySlowBurnGui
g28=FireCutterGui
g29=FireIntensityStickyGui
g30=FireFlameDashGui
g31=FireBurnWrathGui
g32=FireEnflameGui
g33=FireBurnSearGui
g34=FireballFlashGui
g35=FireBubbleDragonGui
g36=FireballShrapnelGui
g37=FireballExplosiveParticlesGui
g38=FireMeltAcidGui
g39=FireMeltEyeForAnEyeGui
g40=FireInflameGui
g41=FireMeltDisableGui
g42=FireMeltCurseGui
g43=FireExplosionCenterShellShockGui
g44=FireExplosionFissionGui
g45=FireChargeFlameGui
g46=FireExplosionDemonBoomGui
g47=FireExplosionChemicalGui
g48=FireConcentratedExplosionHellFireGranadeGui
g49=FireConcentratedExplosionClusterBombGui
g50=FireIncinerateGui
g51=FireConcentratedExplosionStarCutterGui
g52=FireConcentratedExplosionBlackHoleGui
g53=FireIntensityEndlessSpreadGui
g54=FireIntensityEndlessFlameGui
g55=FireFissureGui
g56=FireIntensityStickyGreekFireGui
g57=FireIntensityStickyNapalmGui
g58=FireBurnWrathCharGui
g59=FireBurnWrathWildFireGui
g60=FireSalamanderGui
g61=FireBurnSearCellDeathGui
g62=FireBurnSearThirdDegreeGui
g63=FireballPotassiumLacedGui
g64=FireballConcussiveBlastGui
g65=FireBubbleParadeGui
g66=FireBubbleDragonTwoHeadedGui
g67=FireSpewerFireStormGui
g68=FireInflameDemonicPressenceGui
g69=FireHellFireGui
g70=FireHellFireBrimStoneGui
g71=FireHellFireChaosGui
g72=FireDayOfDemonsGui
g73=FireInflameForTheKingGui
g74=FireChargeFlameStoredFlameGui
g75=FireFlameTorrentGui
g76=FireFlameTorrentHeatVentGui
g77=FireFlameTorrentSunFlareGui
g78=FireArrowOfAmonGui
g79=FireChargeFlameQuickLaunchGui
g80=FireFleameMissileFlareGui
g81=FireIncinerateCremationGui
g82=FireIncinerateAshesToAshesGui
g83=FireBreathBallGui
g84=FireFlameMissileConflagrateGui
g85=FireFissureVolcanoGui
g86=FireFlameEaterGui
g87=FireFlameEaterBoilingBloodGui
g88=FireFlameEaterBurstGui
g89=FirePowerGui
g90=FireFissureCataclysmGui
g91=FireSalamanderBreathOfLifeGui
g92=FireSelfImmolationGui
g93=FireSelfImmolationHellishRewardGui
g94=FireSelfImmolationImmolateGui
g95=FireBloodOfTheDragonGui
g96=FireSalamanderAfterBurnGui
g97=FireSpewerComboGui
g98=FireBubbleDragonDragonDanceGui





}


if OGoblin.form=2

{
g0=EarthGui
g1=EarthGrindGui
g2=EarthVineGui
g3=EarthVenomGui
g4=EarthStalagmiteGui
g5=EarthLordOfFliesGui
g6=EarthFractureGui
g7=EarthRuptureGui
g8=EarthGrowthGui
g9=EarthLeafCutterGui
g10=EarthStabGui
g11=EarthScrapeGui
g12=EarthWildRushGui
g13=EarthSoulRipGui
g14=EarthBeastOfTheEarthGui
g15=EarthBoulderGui
g16=EarthGrindPressureBallsOfIronGui
g17=EarthVineConstrictGui
g18=EarthRavageGui
g19=EarthVineBloomGui
g20=id
g21=EarthVenomNeruoToxinGui
g22=EarthBileGui
g23=EarthVenomSlowDeathGui
g24=EarthStalagmiteColumnGui
g25=EarthRipperGui
g26=EarthStalagmitePierceGui
g27=EarthLordOfFliesInfestationGui
g28=EarthLockJawGui
g29=EarthLordOfFliesPheromoneReleaseGui
g30=id
g31=EarthFractureTraumaGui
g32=EarthSoulTwistGui
g33=EarthFractureGui
g34=EarthGrindDustGui
g35=EarthPlateShiftGui
g36=EarthGrindPressureKineticPotentialGui
g37=EarthGrindPressureBallsOfIronGui
g38=EarthVineConstrictStrangleGui
g39=EarthVineConstrictDeepRootsGui
g40=EarthTreeSpeakGui
g41=EarthVineBloomNightShadeGui
g42=EarthVineBloomSporeCarrierGui
g43=EarthVenomNeruoToxinNecrosisGui
g44=EarthVenomNeruoToxinExcitotoxicityGui
g45=EarthConcoctionGui
g46=EarthVenomSlowDeathMuscleFailureGui
g47=EarthVenomSlowDeathMyotoxinGui
g48=EarthStalagmiteColumnFlowStoneGui
g49=EarthStalagmiteColumnFlowStoneGui
g50=EarthStoneForestGui
g51=EarthStalagmitePierceSplitGui
g52=EarthStalagmitePierceErrodeGui
g53=EarthLordOfFliesInfestationEggBurstGui
g54=EarthLordOfFliesInfestationParasiticHostGui
g55=EarthUnholyFormGui
g56=EarthLordOfFliesPheromoneReleaseEpithelialGlandsGui
g57=EarthLordOfFliesPheromoneReleaseForcedEvolutionGui
g58=EarthFractureTraumaLobotomyGui
g59=EarthFractureTraumaSkeletalFailureGui
g60=EarthSoulStickGui
g61=EarthFractureCrackSplinterGui
g62=EarthFractureCrackSegmentalGui
g63=EarthGrindDustGuiBuildUpGui
g64=EarthGrindDustFlayGui
g65=EarthExtremePressureGui
g66=EarthPlateShiftGui
g67=EarthBoulderBowlingPinsGui
g68=EarthTreeSpeakRampantGui
g69=EarthEntGui
g70=EarthEntWoodenSoliderGui
g71=EarthEntEntwivesGui
g72=EarthTreeOfLifeGui
g73=EarthTreeSpeakVenganceGui
g74=EarthConcoctionRandomIngredientsGui
g75=EarthSnakeBiteGui
g76=EarthSnakeBiteClottingGui
g77=EarthSnakeBiteKingCobraGui
g78=EarthLadyDeathGui
g79=EarthConcoctionRandomIngredientsGui
g80=EarthRipperCrucifyGui
g81=EarthStoneForestKarstRockFormationsGui
g82=EarthStoneForestCalciteGui
g83=EarthBackToTheStoneageGui
g84=EarthRipperSkewerGui
g85=EarthUnholyFormConsumeGui
g86=EarthAbominationGui
g87=EarthAbominationMetamorphGui
g88=EarthAbominationFrenzyGui
g89=EarthWallOfFleshGui
g90=EarthUnholyFormBurrowGui
g91=EarthSoulStickHuskGui
g92=EarthSnapGui
g93=EarthSnapFragmentGui
g94=EarthSnapShatterGui
g95=EarthSacrificeGui
g96=EarthSoulStickWackGui
g97=EarthBoulderPileUpGui
g98=EarthPlateShiftContentialDriftGui





}




if OGoblin.form=3

{
g0=ZapGui
g1=LightningBallLightningGui
g2=LightningElectroKinesisGui
g3=LightningArcFlashGui
g4=ElectrocuteGui
g5=LightningInfusionGui
g6=LightningBoltGui
g7=LightningMagnetismGui
g8=LightningCloudGui
g9=LightningShoutGui
g10=LightningThunderHawkGui
g11=LightningThunderWaveGui
g12=LightningBullRushGui
g13=LightningSlamGui
g14=LightningRodGui
g15=LightningDischargeGui
g16=LightningBallDryStormGui
g17=LightningElectroKinesisArcGui
g18=LightningEyeGui
g19=LightningElectroKinesisStreamGui
g20=id
g21=LightningArcFlashElectricalSurgeGui
g22=LightningSpotLightningGui
g23=LightningArcFlashFlashOverGui
g24=LightningElectrocuteDefibrillatorGui
g25=LightningGroundedGui
g26=LightningElectrocuteNeuropathyGui
g27=LightningInfusionStaticReleaseGui
g28=LightningMineGui
g29=LightningInfusionElectricChairGui
g30=id
g31=LightningBoltDirectStrikeGui
g32=LightningTossGui
g33=LightningBoltSurfaceDischargeGui
g34=LightningBallLightningPlasmaGui
g35=LightningElectricalBreakdownGui
g36=LightningBallDryStormCondensedSupercellGui
g37=LightningBallDryStormArcDischargeGui
g38=LightningElectroKinesisChainLightningGui
g39=LightningElectroKinesisArcJumpingFountainsGui
g40=LightningConstructGui
g41=LightningElectroKinesisStreamThermalRunawayGui
g42=LightningElectroKinesisStreamFulguriteGui
g43=LightningArcFlashElectricalSurgeAtomSplitterGui
g44=LightningArcFlashElectricalSurgeFissionGui
g45=LightningDemonicDischargeRedLightningGui
g46=LightningArcFlashFlashOverSuperHeatedGui
g47=LightningArcFlashFlashOverUltraVioletGui
g48=LightningElectrocuteDefibrillatorCycleGui
g49=LightningElectrocuteDefibrillatorCardiacConductionGui
g50=LightningAsystoleGui
g51=LightningElectrocuteNeuropathyTinglingGui
g52=LightningElectrocuteNeuropathyLossOfControlGui
g53=LightningInfusionStaticReleasePositiveChargeGui
g54=LightningInfusionStaticReleaseCurrentElectricityGui
g55=LightningThunderPunchGui
g56=LightningInfusionElectricChairDancingBoltsGui
g57=LightningInfusionElectricChairVoltageGui
g58=LightningBoltDirectStrikeNervousSystemDamageGui
g59=LightningBoltDirectStrikeInternalBurnsGui
g60=LightningTouchTheSkyGui
g61=LightningBoltSurfaceDischargeWebGui
g62=LightningBoltSurfaceDischargeConductivityGui
g63=LightningBallLightningPlasmaUnstableMatterGui
g64=LightningBallLightningPlasmaDustyPlasmaGui
g65=LightningElectroMagneticPulseGui
g66=LightningElectricalBreakdownLichtenbergFigureGui
g67=LightningDischargeBrushGui
g68=LightningConstructBatteryPoweredGui
g69=LightningElectricHeartGui
g70=LightningElectricHeartRhythmGui
g71=LightningElectricHeartGearUpGui
g72=LightningSymphonyGui
g73=LightningConstructOverVoltGui
g74=LightningDemonicDischargeGui
g75=LightningTempestGui
g76=LightningTempestCat5Gui
g77=LightningTempestGreatRedSpotGui
g78=LightningDemonicRallyGui
g79=LightningDemonicDischargeElectronAvalancheGui
g80=LightningGroundedBondingGui
g81=LightningAsystoleErraticHeartBeatGui
g82=LightningAsystoleHeartAttackGui
g83=LightningFlashStormGui
g84=LightningGroundedIsolationGui
g85=LightningThunderPunchIronBloodGui
g86=LightningDanceGui
g87=LightningDanceElectrifyGui
g88=LightningDanceThunderousDrumsGui
g89=LightningHaloGui
g90=LightningThunderPunchRapidStikesGui
g91=LightningTouchTheSkyReleaseGui
g92=LightningTranscendenceGui
g93=LightningTranscendenceGodSpeedGui
g94=LightningTranscendenceShortCircuitGui
g95=LightningThunderStormGui
g96=LightningTouchTheSkyEletricalImpulseGui
g97=LightningDischargeStElmosfireGui
g98=LightningElectricalBreakdownFractalBurningGui





}

